#!/usr/bin/env python2
"""
    This script helps with setting up the environment.
    Run ./build dependencies, and it setups the environment.
    Run ./build, and it builds the system.
    Building takes some time to finish.
"""
from StringIO import StringIO
from subprocess import call, check_call
from urllib import urlopen
from zipfile import ZipFile
from hashlib import sha256
import argparse, json, os, sys

def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    cmd = subparsers.add_parser('dependencies',
        help="Fetch or build dependencies for building runtime")
    cmd.set_defaults(func=dependencies)

    cmd = subparsers.add_parser('build',
        help="Build the runtime")
    cmd.set_defaults(func=compile_runtime)
    cmd.add_argument("--lldebug", action="store_true",
        help="Produce debugging information")
    cmd.add_argument("--use-pypy", action="store_true",
        help="Use pypy for compiling")

    cmd = subparsers.add_parser('interpret',
        help="Interpret the runtime slowly")
    cmd.set_defaults(func=interpret_runtime)
    cmd.add_argument("--use-pypy", action="store_true",
        help="Use pypy for interpretation")
    cmd.add_argument("--pdb", action="store_true",
        help="Run with a debugger")
    cmd.add_argument("args", nargs="*")

    parser.set_default_subparser("build")

    # TODO: Provide remaining helpers for maintaining the project.

    args = parser.parse_args()
    return args.func(args)

pypy_src_url = 'https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-src'
pypy_src_sha256 = '3553b19447cdb627919cc37d76979e15dc755b085e979f5ffa9b25933ec343b3'
# The project depends on RPython in PyPy branch.
# Everything needed for building this project
# is stored in the build.dir/ subdirectory.
def dependencies(args):
    mkdirs('build.dir')
    config = config_read()

    # You may place a custom pypy into build/pypy directory.
    if os.path.exists(os.path.join('build.dir', 'pypy')):
        pypy_src_dir = os.path.join('build.dir', 'pypy')
    else:
        pypy_src_dir = os.path.join('build.dir',
            os.path.basename(pypy_src_url))
        if not os.path.exists(pypy_src_dir):
            download_and_extract('build.dir', pypy_src_url + ".zip",
                pypy_src_sha256) 

    config['env']['PYTHONPATH'] = pypy_src_dir
    config['rpython_bin'] = os.path.join(pypy_src_dir,
        'rpython', 'bin', 'rpython')

    # TODO: insert the remaining troubleshoot/prebuild handling.

    config_write(config)
    return 0

# RPython script, usually in rpython/bin/rpython, is run with the
# runtime/goal_standalone.py
# This causes the runtime/goal_standalone.py to load and evaluate.
def compile_runtime(args):
    config = config_read()
    rpython_bin = config.get('rpython_bin')
    if rpython_bin is None:
        print("error: build environment has not been properly setup")
        print("Run the following command to set up the environment:")
        print("./build dependencies")
        return 1

    build_flags = []
    #if not args.nojit:
    #    build_flags.append('--translation-jit')
    #build_flags.append('--gc=incminimark')
    #build_flags.append('--opt=2')
    if args.lldebug:
        build_flags.append('--lldebug')

    if args.use_pypy:
        cmd = 'pypy'
    else:
        cmd = 'python'
    for key, value in config.get('env', {}).items():
        os.environ[key] = value
    check_call([cmd, rpython_bin] + build_flags
        + ["runtime/goal_standalone.py"])

# In the early phase of development it was pleasing to check
# results by running the interpreter interpreted.
def interpret_runtime(args):
    config = config_read()
    rpython_bin = config.get('rpython_bin')
    if rpython_bin is None:
        print("error: build environment has not been properly setup")
        return 1
    if args.use_pypy:
        cmd = 'pypy'
    else:
        cmd = 'python'
    flags = []
    if args.pdb:
        flags.extend(["-m", "pdb"])
    for key, value in config.get('env', {}).items():
        os.environ[key] = value
    check_call([cmd] + flags + ["runtime/goal_standalone.py"] + args.args)

# There's a build-time configuration file in build/config.json
# It contains some variables you may change to adjust your build.
def config_read():
    if os.path.exists('build.dir/config.json'):
        with open('build.dir/config.json') as fd:
            return json.load(fd)
    else:
        return {
            'env': {},
        }

def config_write(config):
    with open('build.dir/config.json', 'w') as fd:
        json.dump(config, fd, sort_keys=True, indent=4)

# For now, the build script fetches the latest PyPy source package
# to retrieve the RPython translator.
def download_and_extract(target, archive, checksum):
    print('downloading {}'.format(archive))
    tmp_file = os.path.join(target, os.path.basename(archive))
    url = urlopen(archive)
    length = int(url.info()['Content-Length'])
    bstep = length // 9
    with open(tmp_file, 'wb') as fd:
        for i in range(0, length // bstep + 1):
            data = url.read(bstep)
            fd.write(data)
            print ('_'*i) + '@' + ('_'*(9-i)) + (" {}MB".format(length//1000000) if i==0 else '')
    # Some of this is overcomplicated and was written for fun, but I actually
    # wanted to go into details here. Store the file so that a checksum could
    # be calculated. The checksums provide a much-needed failure if the url
    # contents change silently.
    m = sha256()
    with open(tmp_file, 'rb') as fd:
        m.update(fd.read())
    file_checksum = m.hexdigest()
    assert file_checksum == checksum, (
        "file '{}' checksum check failed\nfile: {}\nhash: {}".format(
            tmp_file, file_checksum, checksum))
    print 'extracting the package to directory: {}'.format(target)
    with open(tmp_file, 'rb') as fd:
        zipfile = ZipFile(fd)
        zipfile.extractall(path=target)

def mkdirs(path):
    try:
        os.makedirs(path)
    except OSError:
        if not os.path.isdir(path):
            raise


def set_default_subparser(self, name, args=None, positional_args=0):
    """default subparser selection. Call after setup, just before parse_args()
    name: is the name of the subparser to call by default
    args: if set is the argument list handed to parse_args()

    , tested with 2.7, 3.2, 3.3, 3.4
    it works with 2.6 assuming argparse is installed
    """
    subparser_found = False
    existing_default = False # check if default parser previously defined
    for arg in sys.argv[1:]:
        if arg in ['-h', '--help']:  # global help if no subparser
            break
    else:
        for x in self._subparsers._actions:
            if not isinstance(x, argparse._SubParsersAction):
                continue
            for sp_name in x._name_parser_map.keys():
                if sp_name in sys.argv[1:]:
                    subparser_found = True
                if sp_name == name: # check existance of default parser
                    existing_default = True
        if not subparser_found:
            # If the default subparser is not among the existing ones,
            # create a new parser.
            # As this is called just before 'parse_args', the default
            # parser created here will not pollute the help output.

            if not existing_default:
                for x in self._subparsers._actions:
                    if not isinstance(x, argparse._SubParsersAction):
                        continue
                    x.add_parser(name)
                    break # this works OK, but should I check further?

            # insert default in last position before global positional
            # arguments, this implies no global options are specified after
            # first positional argument
            if args is None:
                sys.argv.insert(len(sys.argv) - positional_args, name)
            else:
                args.insert(len(args) - positional_args, name)

argparse.ArgumentParser.set_default_subparser = set_default_subparser



if __name__=="__main__":
    sys.exit(main())
